bot_token: 1234567890:ABCDEFGHIJKLMNOUPRSTUWXYZ123456789100

telethon_settings:
  session: PingBot
  auto_reconnect: true
  retry_delay: 15
  connection_retries: -1
  request_retries: 5

  api_id: 1234567
  api_hash: ABCDEFGHIJKLMNOUPRSTUWXYZ1234567

log_level: DEBUG